services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true 
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    shm_size: 512mb
    ports:
      - "6020:5000"
      - "6021:8971"
      - "6022:8554"
      - "6023:8555/tcp"
      - "6023:8555/udp"
    environment:
      - TZ=${TZ}
      - LIBVA_DRIVER_NAME=iHD
      - PLUS_API_KEY=45aa9383-ecc3-453b-8335-481577f549bd:1a79c0215edb8f72d2f97946988f5e7ee48bc93a
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Configuration file
      - ./config.yml:/config/config.yml
      - /mnt/ssd/configs/frigate/config:/config
      # Recordings storage (media drive)
      - /mnt/ssd/frigate/media:/media/frigate
      # Shared memory for performance
      - /dev/shm:/dev/shm
      # Cache
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    cap_add:
      - SYS_NICE
