# yaml-language-server: $schema=http://192.168.5.10:6020/api/config/schema.json

auth:
  enabled: True
  reset_admin_password: False
  cookie_secure: False

#notifications:
#  enabled: True
#  email: mariogk01@gmail.com
#  cooldown: 0

review:
  alerts:
    labels:
      - person
      - face
      - car
      - motorcycle
      - license_plate
      - cat
      - dog

objects:
  track:
    - person
    - face
    - car
    - motorcycle
    - license_plate
    - cat
    - dog

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  alerts:
    retain:
      days: 60
      mode: motion
  detections:
    retain:
      days: 60
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 15

birdseye:
  enabled: True
  inactivity_threshold: 30
  quality: 8
  mode: objects

detect:
  enabled: true

mqtt:
  enabled: False

semantic_search:
  enabled: True
  reindex: False
  model_size: large

face_recognition:
  enabled: True
  unknown_score: 0.8
  save_attempts: 100
  model_size: large

lpr:
  enabled: True
  enhancement: 7
  model_size: large
  device: GPU

detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
  ov_2:
    type: openvino
    device: GPU
  ov_3:
    type: openvino
    device: GPU

model:
  path: plus://75eafa2f3843347dd8e431c1763a0fb8

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  Casa_Placas:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:z159357258@192.168.5.252:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
            - detect
    audio:
      enabled: True
      max_not_heard: 30
      listen:
        - bark
        - scream
        - yell
  #Casa_Fundo:
  #  enabled: True
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://admin:@%2523shinoda100@192.168.1.16:554/cam/realmonitor?channel=1\&subtype=0
  #        roles:
  #          - record
  #          - detect
  #Casa_2:
  #  enabled: True
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://admin:@%2523shinoda100@192.168.1.16:554/cam/realmonitor?channel=2\&subtype=0
  #        roles:
  #          - record
  #          - detect
  #Casa_3:
  #  enabled: True
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://admin:@%2523shinoda100@192.168.1.16:554/cam/realmonitor?channel=3\&subtype=0
  #        roles:
  #          - record
  #          - detect
  #Casa_4:
  #  enabled: True
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://admin:@%2523shinoda100@192.168.1.16:554/cam/realmonitor?channel=4\&subtype=0
  #        roles:
  #          - record
  #          - detect
  #Casa_5:
  #  enabled: True
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://admin:@%2523shinoda100@192.168.1.16:554/cam/realmonitor?channel=5\&subtype=0
  #        roles:
  #          - record
  #          - detect